---
title: "Foreign travel advice"
format:
   html: 
    page-layout: article
    self-contained: true
execute:
  echo: false
  message: false
  warning: false
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse) ; library(rvest) ; library(countrycode) ; library(gt)

countries <- read_csv("data/countries.csv")

# one line travel advice
read_status <- ~{
  message(.)
  read_html(.) |>
    html_nodes("strong") |>
    html_text2() 
}

# date updated
read_updated <- ~{
  message(.)
  read_html(.) |>
    html_nodes(".gem-c-metadata__definition") |>
    html_text2()
}

status <- countries |>
  mutate(status = map(pull(countries, url), read_status)) |>
  unnest(status) |> 
  distinct(name, .keep_all = TRUE) |> 
  select(name, status) 

updated <- countries |>
  mutate(updated = map(pull(countries, url), read_updated)) |>
  unnest(updated) |>
  filter(row_number() %% 3 == 2) |> 
  select(name, updated)

df <- left_join(countries, status, by = "name") |> 
  left_join(updated, by = "name") |> 
  mutate(code = countrycode(name, "country.name", "iso3c"),
         status = 
           case_when(
             str_detect(status, "against all travel") & str_detect(status, "parts") ~ "Advise against all travel to parts", str_detect(status, "against all travel") & !str_detect(status, "parts") ~ "Advise against all travel", str_detect(status, "essential") & str_detect(status, "parts") ~ "Advise against all but essential travel to parts", str_detect(status, "essential") & !str_detect(status, "parts") ~ "Advise against all but essential travel",
             TRUE ~ "Check travel advice before travelling"),
         status = fct_relevel(status, "Advise against all travel", "Advise against all travel to parts", "Advise against all but essential travel", "Advise against all but essential travel to parts"),
    updated = as.Date(updated, format = "%d %b %Y")
    ) |> 
  filter(status != "Check travel advice before travelling") |> 
  arrange(desc(updated))

tbl <- df |> 
  gt(
    rowname_col = "country",
    groupname_col = "status"
  ) |> 
  row_group_order(groups = c("Advise against all travel", "Advise against all travel to parts", "Advise against all but essential travel", "Advise against all but essential travel to parts")) |> 
  fmt_url(
    columns = url,
    label = fontawesome::fa(
      name = "link",
      height = "0.75em",
      vertical_align = "0em"
    ),
    color = "#bdbdbd"
  ) |> 
  cols_merge(
    columns = c(name, url),
    pattern = "{1} {2}"
  ) |> 
  fmt_flag(columns = code) |> 
  cols_merge(
    columns = c(name, code),
    pattern = "{2} {1}"
  ) |>
  fmt_date(
    columns = updated,
    date_style = "day_m_year"
  ) |>
  cols_label(
    name = "",
    updated = "Updated",
  ) |> 
  tab_style(
    style = cell_text(weight = "bold"),
    locations = cells_column_labels()
    ) |> 
  tab_style(
    style = cell_text(weight = "bold"),
    locations = cells_row_groups(groups = everything())
  ) |>
  tab_style(
    style = list(cell_fill(color = "#e31a1c"),
                 cell_text(color = "#FFFFFF")),
    locations = cells_row_groups(groups = "Advise against all travel")
  ) |> 
  tab_style(
    style = list(cell_fill(color = "#fb9a99"),
                 cell_text(color = "#FFFFFF")),
    locations = cells_row_groups(groups = "Advise against all travel to parts")
  ) |> 
  tab_style(
    style = list(cell_fill(color = "#ff7f00"),
                 cell_text(color = "#FFFFFF")),
    locations = cells_row_groups(groups = "Advise against all but essential travel")
  ) |> 
  tab_style(
    style = list(cell_fill(color = "#fdbf6f"),
                 cell_text(color = "#FFFFFF")),
    locations = cells_row_groups(groups = "Advise against all but essential travel to parts")
  ) |> 
  tab_source_note(
    source_note = md("*Source*: UK Foreign, Commonwealth & Development Office")
  ) |> 
  tab_options(
    table.width = pct(100),
    table.align = "left",
    data_row.padding = px(3),
    column_labels.border.top.color = "transparent",
    column_labels.border.bottom.color = "transparent",
    table_body.border.bottom.color = "transparent",
    table.border.bottom.color = "transparent",
    table_body.hlines.color = "gray60",
    quarto.disable_processing = TRUE
    ) |> 
  tab_style(
    style = cell_borders(
      sides = "all",
      weight = px(2),
      color = "#FFFFFF"),
    locations = cells_row_groups()
    )
```

This is the latest travel advice from the UK's [Foreign Commonwealth and Development Office (FCDO)](https://www.gov.uk/government/organisations/foreign-commonwealth-development-office). The information was scraped from the FCDO's [foreign travel advice pages](https://www.gov.uk/foreign-travel-advice).

```{r}
#| label: table
tbl
```

